# Generated by Django 3.2.13 on 2022-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220626_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='confirm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
