# Generated by Django 4.0.6 on 2022-09-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220626_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Address',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='confirm',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
